server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            redirectUri: ${GITHUB_REDIRECT_URI}
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
          facebook:
            clientId: ${FACEBOOK_ID}
            clientSecret: ${FACEBOOK_SECRET}
            scope:
              - public_profile
  datasource:
    url: jdbc:mysql://localhost/flashcards
    username: estudo
    password: ${BD_SECRET}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    defaultSchema: flashcards

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: vgrssdasilva@gmail.com
    password: ${SMTP_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp-relay.sendinblue.com
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
# Chave da conta de serviço (JSON)
gemini:
  #service-account-key-path: file:./credentials.json
  #project-id: ${GEMINI_PROJECT_ID}
  # Audiência da API (ponto de extremidade)
  #audience: https://aiplatform.googleapis.com/v1/projects/${GEMINI_PROJECT_ID}/locations/us-central1/models/gemini-1.0-pro:streamGenerateContent
  key: ${GEMINI_API_KEY}
  url: ${GEMINI_API_URL}

default:
  sender: no-reply@memobeam.site
  recipient: vgrssdasilva@gmail.com
  url: http://localhost:8082

frontend:
  uri: http://localhost:8080

api:
  security:
    token:
      secret: ${JWT_SECRET}
      issuer: VSS Flashcards

dominio:
  regra:
    limite-questoes: ${LIMIT_DE_FLASHCARDS}