server:
  port: 5000

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            redirectUri: ${GITHUB_REDIRECT_URI}
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
          facebook:
            clientId: ${FACEBOOK_ID}
            clientSecret: ${FACEBOOK_SECRET}
            scope:
              - public_profile
  datasource:
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_SECRET}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${SMTP}
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${SMTP}

default:
  sender: ${SMTP_SENDER}
  recipient: ${USR_SMTP}
  url: ${URL_BACK}


frontend:
  uri: ${URL_FRONT}


