server:
  port: 5000

spring:
  datasource:
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_SECRET}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: ${SMTP}
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
      fallback: false
    host: ${SMTP}
    username: ${USR_SMTP}
    password: ${SMTP_SECRET}
    port: 465
    protocol: smtps



default:
  sender: ${USR_SMTP}
  recipient: ${USR_SMTP}
  url: ${URL_BACK}


frontend:
  uri: ${URL_FRONT}


