server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost/flashcards
    username: estudo
    password: ${BD_SECRET}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    defaultSchema: flashcards

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: vgrssdasilva@gmail.com
    password: ${SMTP_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp-relay.sendinblue.com



default:
  sender: no-reply@memobeam.com.br
  recipient: vgrssdasilva@gmail.com
  url: http://localhost:8082


frontend:
  uri: http://localhost:8080


api:
  security:
    token:
      secret: ${JWT_SECRET}
      issuer: VSS Flashcards

