
spring:
  datasource:
    url: jdbc:mysql://localhost/flashcards
    username: estudo
    password: ${BD_SECRET}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET}
      issuer: VSS Flashcards