server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            redirectUri: ${GITHUB_REDIRECT_URI}
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
          facebook:
            clientId: ${FACEBOOK_ID}
            clientSecret: ${FACEBOOK_SECRET}
            scope:
              - public_profile
  datasource:
    url: jdbc:mysql://localhost/flashcards
    username: estudo
    password: ${BD_SECRET}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    defaultSchema: flashcards

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: vgrssdasilva@gmail.com
    password: ${SMTP_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp-relay.sendinblue.com
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false



default:
  sender: no-reply@memobeam.site
  recipient: vgrssdasilva@gmail.com
  url: http://localhost:8082

frontend:
  uri: http://localhost:8080

api:
  security:
    token:
      secret: ${JWT_SECRET}
      issuer: VSS Flashcards
